services:
  # Backend Service
  - type: web
    name: tech-support-backend
    env: docker
    rootDir: .
    region: oregon
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
      - key: CORS_ORIGINS
        value: "https://tech-support-frontend-o842.onrender.com"
      # MongoDB (set value in Render dashboard)
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: chatbot_db
      # Auth/JWT
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXP_MINUTES
        value: "10080"
      # External API keys
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /docs
    autoDeploy: true

  # Frontend Service
  - type: web
    name: tech-support-frontend
    env: docker
    rootDir: .
    region: oregon
    plan: free
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: PORT
        value: "10000"
      - key: NEXT_PUBLIC_API_URL
        value: "https://tech-support-backend.onrender.com"
    healthCheckPath: /
    autoDeploy: true