services:
  # Backend Service
  - type: web
    name: tech-support-backend
    env: docker
    rootDir: .
    region: oregon
    plan: free
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
    healthCheckPath: /docs  # or your health check endpoint
    autoDeploy: true

  # Frontend Service
  - type: web
    name: tech-support-frontend
    env: docker
    rootDir: .
    region: oregon
    plan: free
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      - key: NEXT_PUBLIC_API_URL
        value: https://tech-support-backend.onrender.com  # Update with your backend URL
    autoDeploy: true